name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: "1.8.5"
  WORKING_DIR: "environments/DEV"
  AWS_REGION: "us-east-1"

jobs:
  terraform:
    name: Terraform Validate and Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::653853166958:role/github-actions-terraform-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format
        run: terraform fmt -check -recursive

      # Klasör geçişlerini doğrudan bash komutu içinde 'cd' ile yapıyoruz
      - name: Terraform Init
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform init -input=false

      - name: Terraform Validate
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform validate
      
      - name: Run tfsec (Security Scan)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        run: |
          cd ${{ env.WORKING_DIR }}
          terraform plan -input=false